### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by kobylinskii-m** [murproject/mur_ide#3]
Выдаёт ошибку, когда в первый раз запускаю IDE.
ОС: Windows 7 Максимальная 64
ЦП: Xeon x5460
ОЗУ: 3 гб.
Видеоадаптер: Nvidia GT 9500
Microsoft Visual C++ 2015 установлен
![image](https://user-images.githubusercontent.com/69149831/100081436-f9b54f00-2e81-11eb-90b6-ac927b39de04.png)
![image](https://user-images.githubusercontent.com/69149831/100081483-0a65c500-2e82-11eb-84c3-4e32d763e7ac.png)

**Comment by Zauzolkov** [comment]
Здравствуйте.

> Microsoft Visual C++ **2015** установлен

Для murIDE требуется "Microsoft Visual C++ **2015-2019** redistributable" (обратите внимание, на указанный год\версию, возможно что у вас установлена старая версия, или же по ошибке указали неверно). При установке murIDE должна была также произойти установка данных библиотек, если это не было отменено пользователем.

- Не могли бы вы попробовать установить необходимую версию библиотек? ([ссылка на официальный дистрибутив](https://aka.ms/vs/16/release/vc_redist.x64.exe))
- Попробуйте перезагрузить компьютер :)
- Убедитесь, что в пути установки murIDE отсутствуют русские буквы (желательно оставить стандартный путь)

**Comment by kobylinskii-m** [comment]
Перезагрузка компьютера сработала)
